In [1]:
import pandas as pd
import os
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
import pickle

In [2]:
import pandas as pd
import os

mainpath = r"C:\Users\Alexander\Documents\MLE_ProyectoFinal\data\raw"
filename = "Data_cov.csv"
fullpath = os.path.join(mainpath, filename)

In [3]:
df = pd.read_csv(fullpath, encoding='latin1', sep=';')
df.head(10)

,Sector,Dep,Impactado,Saldo,Desembolso_mes,Saldo Promedio,"Deuda Sistea,",Pasivo,Turismo,Sector de Impacto,Venta,Venta Formal,Pasivo_desembolso,Deuda rezagada va,Deuda rezagada vr,pasivo rezagada va,pasivo rezagada vr,Pasivo_desembolso da,Pasivo_desembolso dr
0,INDUSTRIA,Lima,0,56643.10092,0.0,28321.55046,31365.73,5876.82,0,3,108400.0,43741.08,5876.82,-800.65,-0.024891,830.82,0.164649,830.82,0.164649
1,COMERCIO,Arequipa,0,190313.99460,0.0,63437.99818,64864.99,4467.40,0,4,105300.0,69737.17,4467.40,-2810.52,-0.041529,-7043.43,-0.611896,-7043.43,-0.611896
2,SERVICIO,Amazonas,0,547601.57360,0.0,182533.85790,200239.32,5000.92,0,1,86600.0,79178.83,5000.92,653.68,0.003275,2000.92,0.666973,2000.92,0.666973
3,INDUSTRIA,Lima,0,283914.20840,0.0,94638.06947,112945.17,325.50,0,3,103000.0,0.00,325.50,14820.77,0.151041,-17128.30,-0.981351,-17128.30,-0.981351
4,COMERCIO,Cusco,0,142296.43840,0.0,47432.14612,144877.21,0.00,0,4,172920.0,171999.33,0.00,17468.60,0.137107,-2071.80,-1.000000,-2071.80,-1.000000
5,COMERCIO,Lima,0,456005.09530,0.0,152001.69840,136066.81,0.07,0,1,188660.0,0.00,0.07,-6302.57,-0.044269,0.00,0.000000,0.00,0.000000
6,COMERCIO,La Libertad,0,76984.28362,0.0,25661.42787,66740.43,7650.64,0,1,22055.0,5000.00,7650.64,-5973.05,-0.082145,248.61,0.033587,248.61,0.033587
7,COMERCIO,Lima,0,235218.90890,0.0,78406.30297,75528.86,116242.11,0,3,97400.0,5977.67,116242.11,1442.01,0.019464,-96110.34,-0.452598,-96110.34,-0.452598
8,COMERCIO,Cajamarca,0,531200.54440,0.0,177066.84810,177393.15,0.00,0,4,441000.0,32673.33,0.00,-73855.46,-0.293954,-55000.00,-1.000000,-55000.00,-1.000000
9,COMERCIO,Moquegua,0,138737.75300,0.0,46245.91766,47034.40,688.55,0,3,105000.0,0.00,688.55,-2250.13,-0.045656,-81172.46,-0.991589,-81172.46,-0.991589

In [4]:
df.Impactado = df.Impactado.replace({0: "No", 1: "Si"})
X = df.iloc[:, 3:16]
y = df.Impactado

In [5]:
X_std = StandardScaler().fit_transform(X)

In [6]:
train_x, test_x, train_y, test_y = train_test_split(X_std, y, test_size=0.2, random_state=42)

In [7]:
best = SelectKBest(k=5)
X_train_new = best.fit_transform(train_x, train_y)

In [8]:
with open('selectkbest_model.pkl', 'wb') as f:
    pickle.dump(best, f)

In [9]:
with open('selectkbest_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

In [10]:
selected_indices = best.get_support(indices=True)
selected_features = X.columns[selected_indices]
print("Características seleccionadas:", selected_features)

Características seleccionadas: Index(['Saldo', 'Saldo Promedio', 'Pasivo', 'Sector de Impacto',
       'Pasivo_desembolso'],
      dtype='object')